version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/spring-prj
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: start_application.sh
      timeout: 120
      runas: ec2-user
