name: Java CI/CD to CodeDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Make a directory
      run: mkdir deploy
    - name: Copy jar file to "deploy" directory
      run: cp ./build/libs/*.jar ./deploy/
    - name: Make a zip file
      run: zip -r -qq -j ./spring-cicd-build.zip ./deploy
    - name: Deliver the zip file to S3 bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./spring-cicd-build.zip s3://github-actions-deploy-spring/
